apiVersion: v1
kind: ServiceAccount
metadata:
 name: secretmgr-app-sa
automountServiceAccountToken: false
---
apiVersion: v1
kind: Pod
metadata:
  name: secretmgr-app-pod
spec:
  serviceAccount: secretmgr-app-sa
  containers:
  - name: awscli-container
    image: public.ecr.aws/aws-cli/aws-cli:2.15.0
    securityContext:
      runAsNonRoot: true
      allowPrivilegeEscalation: false
      runAsUser: 1
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
---
